### ISSUE TITLE
Elementi di stile condivisi da tutti i template [CSS]

### ISSUE THREAD

**Issue by stoccotommaso02** [stoccotommaso02/fandomia#12]

**Comment by josephgrant26** [comment]
elementi da definire:

pallette colori
bottoni
link
menu

**Comment by josephgrant26** [comment]
bottoni: https://getcssscan.com/css-buttons-examples

Per me bottone 4, bottone 13

**Comment by josephgrant26** [comment]
![pallette 1](https://github.com/user-attachments/assets/b0d1cd31-e863-4149-8570-cb7c354cbf5a)
![pallette 2](https://github.com/user-attachments/assets/8317fbbe-ea09-4d5f-b415-25ea9c0b1a4a)
![pallette 3](https://github.com/user-attachments/assets/8585fdab-4b13-4d18-9fe4-ef5aee6fde60)
![pallette 4](https://github.com/user-attachments/assets/0218638a-ef03-4aa1-9c14-1eda345bb3e0)
![pallette 5](https://github.com/user-attachments/assets/a04efd60-a00d-4a94-b4a3-0c7d4b000698)



pallettes per il sito. tutte hanno colori che rispettano le norme WCAG AA
