### ISSUE TITLE
Pagina-Risultati [HTML]

### ISSUE THREAD

**Issue by IuliusSignorelli** [stoccotommaso02/fandomia#18]
Se nell'header mettiamo la classica barra di ricerca, necessiteremo di una pagina apposta che mostra i risultati di tale ricerca.

**Comment by josephgrant26** [comment]
Per me si puo' riciclare la stessa schermata della vista dei prodotti ma ordinati per best match

**Comment by IuliusSignorelli** [comment]
Io pensavo in generale di filtrare i risultati della ricerca utilizzando come criterio solo la corrispondenza con il titolo del prodotto per semplicità
