### ISSUE TITLE
Pagina del prodotto [HTML]

### ISSUE THREAD

**Issue by stoccotommaso02** [stoccotommaso02/fandomia#7]

**Comment by MartyrVael** [comment]
ho pushato un file, per ora abbastanza fumoso, per una possibile configurazione per la pagina di un qualsiasi prodotto (solo html, non ho ancora fatto il css); ditemi che ne pensate, o se avete consigli/critiche/qualsiasi altra cosa da condividere.

**Comment by MartyrVael** [comment]
Ho cercato di farlo seguendo un po` le direttive di quello che ho visto a lezione di lab della prof, ma non so se per questa pagina specifica possa andare bene l'implementazione scelta

**Comment by MartyrVael** [comment]
Principalmente l'utilizzo di <dl><dt><dd>, che, sempre che non ricordi male, aveva detto essere congeniali all'utilizzo di strumentazioni per la lettura schermo o comunque in generale per l'accessibilità; considerato che teoricamente i dati noi non li andiamo più a toccare dopo aver generato la pagina, credo possa andare bene come struttura dati; poi ho pensato di inserirli comunque in una section, anche se appunto non so se serva veramente in questo caso, o se complichi inutilmente il codice.
Ultima nota, ho messo le class un po' alla rinfusa, provvederò in un secondo momento a metterle nei posti giusti e a toglierle dove non servono.
