### ISSUE TITLE
Lista dei prodotti per categorie [HTML]

### ISSUE THREAD

**Issue by stoccotommaso02** [stoccotommaso02/fandomia#8]

**Comment by josephgrant26** [comment]
[categories.txt](https://github.com/user-attachments/files/16404098/categories.txt)

una prima bozza di categorie, che ne pesnate?

**Comment by IuliusSignorelli** [comment]
Come bozza ci sta, come gestiamo la categoria e sub-categoria? due attributi in più nel DB?

**Comment by stoccotommaso02** [comment]
L'opzione migliore, se vogliamo renderla scalabile (quindi più di una/due categorie), è creare una tabella per categorie, e una che linka ciascun prodotto a tutte le catgorie a cui appartiene

**Comment by stoccotommaso02** [comment]
`CREATE TABLE categories (
  product_id INT UNSIGNED NOT NULL,
  category_name VARCHAR(100) NOT NULL,
  PRIMARY KEY(product_id, category_name),
  FOREIGN KEY(prdouct_id) REFERENCES products(id)
);`

Potrebbe essere una possibilità, un'altra:
`CREATE TABLE ProductCategories (
  product_id INT UNSIGNED NOT NULL,
  category_id INT UNSIGNED NOT NULL,
  PRIMARY KEY(product_id, category_id),
  FOREIGN KEY(product_id) REFERENCES products(id),
  FOREIGN KEY(category_id) REFERENCES Categories(id)
);

CREATE TABLE Categories (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  PRIMARY KEY(id)
)`
La seconda renderebbe più veloce eventuali modifiche alla categoria ecc., diciamo che su un db relativamente ristretto come il nostro può essere indifferente

**Comment by IuliusSignorelli** [comment]
A livello di pagina invece? I prodotti sono mostrati per raffinamenti successivi?
